export const SearchActions = {
    'FETCH_RESULTS': 'FETCH_RESULTS',
    'FETCHED_RESULTS': 'FETCHED_RESULTS',
    'POPULATE_PREVIOUS_SEARCHES': 'POPULATE_PREVIOUS_SEARCHES',
    'CLEAR_PREVIOUS_SEARCHES': 'CLEAR_PREVIOUS_SEARCHES'
};